### ISSUE TITLE
Some troubles and rampant speculation. 

### ISSUE THREAD

**Issue by dcmorse** [jbro/vscode-default-keybindings#21]
I'm on Linux. I'm pretty new to VS Code so apologies in advance. 

I install the extension. 

The doc says to go to Preferences -> Extensions -> VSCode Default Keybindings. 

When I go there the page looks like this, and I am stuck.

![Screenshot from 2024-12-10 17-41-46](https://github.com/user-attachments/assets/d4358193-a9b1-4292-9b79-363a5356503a)

_Somehow_ that I cant' reproduce, I got a tab open that looks like this, and I checked the two boxes you see:

![Screenshot from 2024-12-10 17-45-36](https://github.com/user-attachments/assets/333745ce-8105-44a9-b5a4-a50da8e793a7)

Then I go to a text editing tab, press Menu > Edit, and it tells me Cut/Copy/Paste is Super-x, Super-c, and Super-v. They don't work. There is a key Super on one of my keyboards, but it's captured by the window manager. 

In my opinion, the key that's the logically right one to choose is not Super, it's Alt - it's in the physical space where the command key should be.

**Comment by jbro** [comment]
Hi there, thanks for raising the issue. I'm quite happy with using super as command on Linux.
